- name: csv1
  hosts: localhost
  tasks:
  - name: Path to CSV, delimeter $, register to object users, localhost
    community.general.read_csv:
      path: Alamogordo.csv
      delimiter: $
    register: jinja
    delegate_to: localhost

  - name: Jinja Template
    template:
      src: Alamogordo.j2
      dest: "/var/lib/awx/projects/_73__alamogordo/config/{{ item.hostname }}.txt"
    loop: "{{ jinja.list }}"
