- name: csv
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: Path to CSV, delimeter $, register to object users, localhost
    community.general.read_csv:
      path: Alamogordo.csv
      delimiter: $
    register: jinja
    delegate_to: localhost

  - name: Svi Template
    vars:
      csvfile: "{{ lookup('file', 'svi.csv') }}"
    tasks:
      - name: Parse CSV To YAML
        template:
          src: "./svi.j2"
          dest: "/var/lib/awx/projects/_73__alamogordo/svi_output.txt"
        run_once: true
