---
- hosts: all
  gather_facts: False
  tasks:
    - name: config soufce from jinja2
      arubaoss_config:
        src: /var/lib/awx/projects/_73__alamogordo/config/{{inventory_hostname}}.cfg
        match: line
        timeout: 60
       
