---
- hosts: all
  gather_facts: False
  tasks:
    - debug: msg="{{item}} test"
      with_lines: cat /var/lib/awx/projects/_73__alamogordo/config/{{inventory_hostname}}.cfg       
    - name: config soufce from jinja2
      arubaoss_config:
        src: /var/lib/awx/projects/_73__alamogordo/config/{{inventory_hostname}}.cfg
        match: none       
