---
- hosts: all
  collections:
    - arubanetworks.aos_switch
  gather_facts: False
  tasks:
    - name: config soufce from jinja2
      arubaoss_config:
        src: /var/lib/awx/projects/_73__alamogordo/config/{{inventory_hostname}}.cfg
        match: none
        port: 22
        password: Pr0curve
