---
- hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars:
    csvfile: "{{ lookup('file', 'svi.csv') }}"
  tasks:
    - name: Parse CSV To YAML
      template:
        src: "./svi.j2"
        dest: "./svi_output.yml"
      run_once: true
